### PR TITLE
Interaction handler keyboard handlers fix

### LINKED ISSUE #3536: Interaction handler keyboard events are registered twice
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Interaction handler event listeners should be registered only once

### Current Behaviour

Currently keyup and keydown listeners are registered twice

### Possible Solution

Remove event listeners when interactionHandler class is deleted

### Steps to Reproduce (for bugs)

1. Set up breakpoint on window.addEventListener('keyup') in interactionHandler constructor
1. Notice that application stops twice

### Your Environment

- Git hash commit (`git log -1`): f2c9dc058e9942ed14939c3141967880ed3fe742
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolved #3536 
The problem was caused by creating new Canvas() instance on each GET_JOB_SUCCESS action. Keyboard handlers are registered in constructor, so each new Canvas produces new handler. 
It was solved by additional `destroy() `canvas method which emits `canvas.destroy` and `svgjs destroy` events. Interacton hanlder keyboard handlers are removed in case of such events.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-ui/src/reducers/annotation-reducer.ts [hunk 1]
```diff
@@ -166,6 +166,8 @@ export default (state = defaultState, action: AnyAction): AnnotationState => {
                 activeShapeType = ShapeType.CUBOID;
             }
 
+            state.canvas.instance.destroy();
```
Comment (ActiveChooN) [inline cvat-ui/src/reducers/annotation-reducer.ts:169]: Why not put it in the appropriate action?

**Review by ActiveChooN — COMMENTED** [review]
Please, add the canvas method to the README.md file and adjust package versions.

File: cvat-ui/src/reducers/annotation-reducer.ts (hunk 1 above)
Comment (klakhov) [reply cvat-ui/src/reducers/annotation-reducer.ts]: I've put it into `AnnotationActionTypes.DESTROY_CANVAS` action

File: cvat-ui/src/actions/boundaries-actions.ts [hunk 2]
```diff
@@ -43,6 +43,7 @@ export function resetAfterErrorAsync(): ThunkAction {
             const state = getState();
             const job = state.annotation.job.instance;
 
+            dispatch(createAction(AnnotationActionTypes.DESTROY_CANVAS));
```
Comment (ActiveChooN) [inline cvat-ui/src/actions/boundaries-actions.ts:46]: Why do not put the `destroy` method call here itself, why do we need an additional reducer?

**Review by ActiveChooN — DISMISSED** [review]

File: cvat-ui/src/actions/boundaries-actions.ts (hunk 2 above)
Comment (klakhov) [reply cvat-ui/src/actions/boundaries-actions.ts]: Done

File: cvat-canvas/src/typescript/canvasView.ts [hunk 3]
```diff
@@ -1369,6 +1370,18 @@ export class CanvasViewImpl implements CanvasView, Listener {
...
 
+    public destroy(): void {
+        this.canvas.dispatchEvent(
+            new CustomEvent('canvas.destroy', {
+                bubbles: false,
+                cancelable: true,
+            }),
+        );
+        // We can't call namespaced svgjs event
+        // see - https://svgjs.dev/docs/2.7/events/
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/canvasView.ts:1381]: What exactly should I see? 

I read:

```
SVG.js supports namespaced events following the syntax event.namespace.

A namespaced event behaves like a normal event with the difference that you can remove it without touching handlers from other namespaces.
```

File: cvat-canvas/src/typescript/interactionHandler.ts [hunk 4]
```diff
@@ -375,6 +375,27 @@ export class InteractionHandlerImpl implements InteractionHandler {
         return false;
     }
 
+    private onKeyUp = (e:KeyboardEvent):void => {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/interactionHandler.ts:378]:
```suggestion
    private onKeyUp = (e: KeyboardEvent): void => {
```
```suggestion
    private onKeyUp = (e:KeyboardEvent):void => {
```

File: cvat-canvas/src/typescript/interactionHandler.ts [hunk 5]
```diff
@@ -375,6 +375,27 @@ export class InteractionHandlerImpl implements InteractionHandler {
...
+                this.interactionData.onChangeToolsBlockerState('keyup');
+            }
+            if (this.shouldRaiseEvent(false)) {
+                // 17 is ctrl
+                this.onInteraction(this.prepareResult(), true, false);
+            }
+        }
+    };
+
+    private onKeyDown = (e:KeyboardEvent):void => {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/interactionHandler.ts:390]:
```suggestion
    private onKeyDown = (e: KeyboardEvent): void => {
```
```suggestion
    private onKeyDown = (e:KeyboardEvent):void => {
```

File: cvat-canvas3d/src/typescript/canvas3dView.ts [hunk 6]
```diff
@@ -1875,4 +1877,11 @@ export class Canvas3dViewImpl implements Canvas3dView, Listener {
             front: this.views.front.renderer.domElement,
         };
     }
+
+    public destroy(): void {
+        this.dispatchEvent(new CustomEvent('canvas.destroy', {
```
Comment (bsekachev) [inline cvat-canvas3d/src/typescript/canvas3dView.ts:1882]: what is ``this`` here? Is it a DOM element? 
I am not sure, the current implementation makes sense, maybe just left empty API method that does nothing and implement it later when we will now what this API method should do in canvas3d

File: cvat-ui/src/actions/annotation-actions.ts [hunk 7]
```diff
@@ -1024,6 +1024,8 @@ export function getJobAsync(tid: number, jid: number, initialFrame: number, init
 
             loadJobEvent.close(await jobInfoGenerator(job));
 
+            state.annotation.canvas.instance.destroy();
```
Comment (bsekachev) [inline cvat-ui/src/actions/annotation-actions.ts:1027]: I believe, better to call this method in reducer before we reinitialize canvas. 
Looking this code, not clear why we should destroy current canvas.

File: cvat-ui/src/actions/boundaries-actions.ts [hunk 8]
```diff
@@ -43,6 +43,8 @@ export function resetAfterErrorAsync(): ThunkAction {
             const state = getState();
             const job = state.annotation.job.instance;
 
+            state.annotation.canvas.instance.destroy();
```
Comment (bsekachev) [inline cvat-ui/src/actions/boundaries-actions.ts:46]: The same comment, not very clear, why we call destroy() here.

File: CHANGELOG.md [hunk 9]
```diff
@@ -51,6 +51,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Helm settings for external psql database were unused by backend (<https://github.com/openvinotoolkit/cvat/pull/3779>)
 - Updated WSL setup for development (<https://github.com/openvinotoolkit/cvat/pull/3828>)
 - Helm chart config (<https://github.com/openvinotoolkit/cvat/pull/3784>)
+- Fixed Interaction handler keyboard handlers (<https://github.com/openvinotoolkit/cvat/pull/3881>)
```
Comment (bsekachev) [inline CHANGELOG.md:54]: 1.7 has been just release, please update this file

Comment (klakhov) [reply CHANGELOG.md]: Done.

File: cvat-ui/src/actions/boundaries-actions.ts (hunk 8 above)
Comment (klakhov) [reply cvat-ui/src/actions/boundaries-actions.ts]: Moved it back to reducer

File: cvat-ui/src/actions/annotation-actions.ts (hunk 7 above)
Comment (klakhov) [reply cvat-ui/src/actions/annotation-actions.ts]: Moved it back to reducer

File: cvat-canvas3d/src/typescript/canvas3dView.ts (hunk 6 above)
Comment (klakhov) [reply cvat-canvas3d/src/typescript/canvas3dView.ts]: Made empty destroy method in canvas3dModel

File: cvat-canvas/src/typescript/interactionHandler.ts (hunk 5 above)
Comment (klakhov) [reply cvat-canvas/src/typescript/interactionHandler.ts]: Done

File: cvat-canvas/src/typescript/interactionHandler.ts (hunk 4 above)
Comment (klakhov) [reply cvat-canvas/src/typescript/interactionHandler.ts]: Done

File: cvat-canvas/src/typescript/canvasView.ts (hunk 3 above)
Comment (klakhov) [reply cvat-canvas/src/typescript/canvasView.ts]: Yes, it says it supports namespaced events, but however we can't call it directly. That's what I've meant here.
In the end of this page there is:
```
However, you can't fire a specific namespaced event. Calling element.fire('myevent.namespace') won't do anything while element.fire('myevent') works and fires all attached handlers of the event
```
Maybe it's better to update this comment this way
```// We can't call a specific namespaced event ```

File: cvat-ui/src/reducers/annotation-reducer.ts (hunk 1 above)
Comment (bsekachev) [reply cvat-ui/src/reducers/annotation-reducer.ts:169]: Did you comment these updates? Only annotation-reducer.ts was changed in this patch.

Comment (bsekachev) [reply cvat-ui/src/reducers/annotation-reducer.ts:169]: From ``cvat-ui/``

Comment (bsekachev) [reply cvat-ui/src/reducers/annotation-reducer.ts:169]: And should not we call destroy in BoundariesActionTypes.RESET_AFTER_ERROR action?

Comment (klakhov) [reply cvat-ui/src/reducers/annotation-reducer.ts:169]: I dont think we should call destroy in that action because in `annotation-reducer.ts` there are this kind of code:
```
case BoundariesActionTypes.RESET_AFTER_ERROR:
case AnnotationActionTypes.GET_JOB_SUCCESS: {
...
state.canvas.instance.destroy();
...
```
So probably there is no need to duplicate it in action

Comment (bsekachev) [reply cvat-ui/src/reducers/annotation-reducer.ts:169]: Sure, got it.

**Review by bsekachev — APPROVED** [review]
