### PR TITLE
Fixed bug: Incorrect point deletion with keyboard shortcut

### LINKED ISSUE #3821: point delete bug
### My actions before raising this issue
- [ ] similar to https://github.com/openvinotoolkit/cvat/issues/1391

### Expected Behaviour
just remove one point

### Current Behaviour
random point is removed

### Steps to Reproduce (for bugs)

1.   https://u.pcloud.link/publink/show?code=XZkKiEXZqcJUymaSNN5fOUnR05q1LhmNYLvX

### Your Environment
Server version: 1.6
Core version: 3.16.0
Canvas version: 2.7.0
UI version: 1.23.1
linux

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

The point deletion with shortcut works not quite well if we start deleting points from another shape holding `Alt`
bug

Solution: implement the same behavior with points shape as with polylines. If we are holding `Alt` over one object, another one shouldn't be activated.
polyline

Result:
solution

Resolved #3821 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] ~~I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by klakhov** [comment]
@ActiveChooN Could you look on this fix, please?

**Review by ActiveChooN — APPROVED** [review]
LGTM, would you add tests for the issue in this PR?

**Comment by klakhov** [comment]
Yes, as a next step in this pr test will be added

**Comment by klakhov** [comment]
@bsekachev Could you look on this pr?

File: tests/cypress/integration/issues_prs2/issue_3821_delete_point.js [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+            { x: 330, y: 450 },
+        ],
+    };
+
+    before(() => {
+        cy.openTaskJob(taskName);
+    });
+
+    describe(`Testing issue "${issueId}"`, () => {
+        it('Crearte points shapes', () => {
```
Comment (bsekachev) [inline tests/cypress/integration/issues_prs2/issue_3821_delete_point.js:36]:
```suggestion
        it('Create points shapes', () => {
```

**Comment by bsekachev** [comment]
Still reproducable using Ctrl
test

File: tests/cypress/integration/issues_prs2/issue_3821_delete_point.js [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+                });
+        });
+        it('Point must be removed from first shape, second one should stay the same', () => {
+            cy.get('#cvat_canvas_shape_1')
+                .children()
+                .should('have.length', 2);
+            cy.get('#cvat_canvas_shape_2')
+                .children()
+                .should('have.length', 3);
+        });
```
Comment (bsekachev) [inline tests/cypress/integration/issues_prs2/issue_3821_delete_point.js:71]: It should be the same it(). In the first you do not check anything.

File: tests/cypress/integration/issues_prs2/issue_3821_delete_point.js [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+    before(() => {
+        cy.openTaskJob(taskName);
+    });
+
+    describe(`Testing issue "${issueId}"`, () => {
+        it('Crearte points shapes', () => {
+            cy.createPoint(firstPointsShape);
+            cy.get('#cvat-objects-sidebar-state-item-1').should('contain', '1').and('contain', 'POINTS SHAPE');
+            cy.createPoint(secondPointsShape);
+            cy.get('#cvat-objects-sidebar-state-item-2').should('contain', '2').and('contain', 'POINTS SHAPE');
```
Comment (bsekachev) [inline tests/cypress/integration/issues_prs2/issue_3821_delete_point.js:40]: Probably it should be a part of ``before`` section because we do not test creating points here

File: cvat-canvas/src/typescript/canvasView.ts [hunk 4]
```diff
@@ -875,7 +886,22 @@ export class CanvasViewImpl implements CanvasView, Listener {
...
                         });
 
-                    circle.on('mouseenter', (): void => {
+                    circle.on('mouseenter', (e: MouseEvent): void => {
+                        const activeElement = getActiveElement();
+                        if (activeElement !== null && e.altKey) {
+                            const [state] = getController().objects.filter(
+                                (_state: any): boolean => _state.clientID === activeElement.clientID,
+                            );
+                            if (state.shapeType === 'points') {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/canvasView.ts:895]:
```suggestion
                            if (state?.shapeType === 'points') {
```

File: cvat-canvas/src/typescript/canvasView.ts [hunk 5]
```diff
@@ -875,7 +886,22 @@ export class CanvasViewImpl implements CanvasView, Listener {
...
+                                const selectedClientID = parseInt(
+                                    ((e.target as HTMLElement).parentElement as HTMLElement).getAttribute('clientID'), 10,
+                                );
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/canvasView.ts:898]: Why not to use + operator here to cast to integer? It looks simpler

File: cvat-canvas/src/typescript/canvasView.ts (hunk 4 above)
Comment (bsekachev) [reply cvat-canvas/src/typescript/canvasView.ts:895]: Maybe this condition should work for all the shapes, not only for points, do not you think so?

**Review by bsekachev — APPROVED** [review]
