### PR TITLE
Fixed polygon editing

### LINKED ISSUE #2807: Issues with polyline editing
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a polyline, start editing it from the center (Shift + Click)
1. Draw correcting line
1. Move mouse a bit, try to press the latest drawn button again 
1. The button is expected to be highlighted on hover and pressing it closes editing mode (Actually this condition is false)

### Your Environment

- Git hash commit (`git log -1`): e43707d779fec

### PR DESCRIPTION
**Pull request by bsekachev**
Resolved #2807 
The bug appeared with this PR #2276 because of changing in implementation of svg.draw.js

@dvkruchinin Could you please write a test? Steps are described in the issue

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-canvas/src/typescript/editHandler.ts [hunk 1]
```diff
@@ -103,7 +105,7 @@ export class EditHandlerImpl implements EditHandler {
 
         this.editLine = (this.canvas as any).polyline();
         if (this.editData.state.shapeType === 'polyline') {
-            (this.editLine as any).on('drawpoint', (e: CustomEvent): void => {
+            (this.editLine as any).on('drawupdate', (e: CustomEvent): void => {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/editHandler.ts:108]: Only actual change in the PR. Others are to fix linter issues

**Comment by dvkruchinin** [comment]
> Could you please write a test? Steps are described in the issue

Sure. The test will be written.

File: cvat-canvas/src/typescript/editHandler.ts (hunk 1 above)
Comment (nmanovic) [reply cvat-canvas/src/typescript/editHandler.ts:108]: It is an extremely useful comment.
