### PR TITLE
Large files uploads

### LINKED ISSUE #956: Support uploading big files using a browser
I'm trying to upload video of size 2GB and webpage show me error just after few second 

Could not create the task
Error: Network Error.

and I've checked it works with videos of size 100mb

### LINKED ISSUE #2332: Uploading huge yolo dataset causes error 500
I have 11G zip yolo dataset. When I try to upload it through web interface, i get these errors:

```
Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at create-task-content.tsx:156
:8080/api/v1/jobs/5/annotations?format=YOLO%201.1:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
cvat-app.tsx:217 Error: Request failed with status code 500. "Exception: Can't find image info for '/tmp/tmpnq5lma66/obj_train_data/frame_000000.png'\n".
e @ cvat-app.tsx:217
:8080/api/v1/tasks/6/data:1 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
cvat-app.tsx:217 Error: Request failed with status code 413. "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>413 Request Entity Too Large</title>\n</head><body>\n<h1>Request Entity Too Large</h1>\nThe requested resource does not allow request data with POST requests, or the amount of data provided in\nthe request exceeds the capacity limit.\n</body></html>\n".
```
how can we fix or workaround this?

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolved #956
Resolved #2332
Resolved https://github.com/openvinotoolkit/cvat/issues/1616
Fixed large files uploading via webpage, implemented using chunk file uploads with upload progress bar.
Peek 2021-09-21 11-55

### How has this been tested?

Manually tested with large videos, archives, 20k images

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-core/src/server-proxy.js [hunk 1]
```diff
@@ -595,6 +595,11 @@
                 }
 
                 const taskData = new FormData();
+
+                const clientFile = taskDataSpec.client_files[0];
+                const clientFiles = taskDataSpec.client_files;
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:600]: Just newer syntax to get the first element of an array is:

const clientFiles = taskDataSpec.client_files;
const [clientFile] = clientFiles;

File: cvat-core/src/server-proxy.js [hunk 2]
```diff
@@ -595,6 +595,11 @@
...
+                const uploadUsingChunks = clientFiles.length === 1;
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:601]: I would suggest also checking if the file size more than chunkSize you use.

File: cvat-core/src/server-proxy.js [hunk 3]
```diff
@@ -619,19 +624,91 @@
...
+                        } catch (errorData) {
+                            try {
+                                await deleteTask(response.data.id);
+                            } catch (_) {
+                                // ignore
+                            }
+                            throw generateError(errorData);
+                        }
                     }
+                    await upload();
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:656]: Do you really need recursion here? Just I think it would look more natural in ``while``

File: cvat-core/src/server-proxy.js [hunk 4]
```diff
@@ -619,19 +624,91 @@
...
-                        // ignore
+                onUpdate('The data are being uploaded to the server 0%');
+
+                async function chunkUpload(file) {
+                    const chunkSize = 1024 * 1024 * 100; // 100 mb
+                    const totalChunks = Math.ceil(file.size / chunkSize);
+                    let currentChunkNumber = 1;
+                    async function upload() {
+                        const prevChunkNumber = currentChunkNumber - 1;
+                        const fileChunk = file.slice(prevChunkNumber * chunkSize, Math.min(prevChunkNumber * chunkSize + chunkSize, file.size));
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:635]:
```suggestion
                        const chunkOffset = prevChunkNumber * chunkSize;
                        const fileChunk = file.slice(chunkOffset, Math.min(chunkOffset + chunkSize, file.size));
```

File: cvat-core/src/server-proxy.js [hunk 5]
```diff
@@ -619,19 +624,91 @@
...
+                        taskData.set('chunk_file_name', file.name);
+                        taskData.set('end_of_upload', currentChunkNumber >= totalChunks);
+                        taskData.set('use_chunk_upload', true);
+                        try {
+                            await Axios.post(`${backendAPI}/tasks/${response.data.id}/data`, taskData, {
+                                proxy: config.proxy,
+                            });
+                            onUpdate(`The data are being uploaded to the server ${Math.round((currentChunkNumber / totalChunks) * 100)}%`);
+                            currentChunkNumber++;
+                            if (currentChunkNumber <= totalChunks) await upload();
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:646]: Do not need try inside if we wrap the function call (chunkUpload and bulkUpload).

File: cvat-core/src/server-proxy.js [hunk 6]
```diff
@@ -619,19 +624,91 @@
...
+                        } catch (errorData) {
+                            try {
+                                await deleteTask(response.data.id);
+                            } catch (_) {
+                                // ignore
+                            }
+                            throw generateError(errorData);
+                        }
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:702]: The same comment about try block. Better to put it outside.

File: cvat-core/src/server-proxy.js [hunk 7]
```diff
@@ -619,19 +624,91 @@
...
+                        });
+                        taskData.set('end_of_upload', currentChunkNumber >= totalChunks);
+                        taskData.set('use_chunk_upload', false);
+                        try {
+                            await Axios.post(`${backendAPI}/tasks/${response.data.id}/data`, taskData, {
+                                proxy: config.proxy,
+                            });
+                            onUpdate(`The data are being uploaded to the server ${Math.round((currentChunkNumber / totalChunks) * 100)}%`);
+                            currentChunkNumber++;
+                            if (currentChunkNumber <= totalChunks) await upload();
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:694]: Better to avoid recursion here

File: cvat-core/src/server-proxy.js [hunk 8]
```diff
@@ -619,19 +624,91 @@
...
+
+                async function chunkUpload(file) {
+                    const chunkSize = 1024 * 1024 * 100; // 100 mb
+                    const totalChunks = Math.ceil(file.size / chunkSize);
+                    let currentChunkNumber = 1;
+                    async function upload() {
+                        const prevChunkNumber = currentChunkNumber - 1;
+                        const fileChunk = file.slice(prevChunkNumber * chunkSize, Math.min(prevChunkNumber * chunkSize + chunkSize, file.size));
+                        taskData.set('client_files[0]', fileChunk);
+                        taskData.set('chunk_file_name', file.name);
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:637]: Can we get file name from the uploaded file after it is fully uploaded?

File: cvat-core/src/server-proxy.js [hunk 9]
```diff
@@ -619,19 +624,91 @@
...
+                        taskData.set('end_of_upload', currentChunkNumber >= totalChunks);
+                        taskData.set('use_chunk_upload', true);
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:639]: According to current design I think we should use query parameters instead of body arguments. 
?action=append (on the server can we understand what data client sent (chunk of a single file, or one file? If yes, we do not need different flags to chunks and bulks))
?action=submit (end of upload sent in a different request with no data)

File: cvat-core/src/server-proxy.js [hunk 10]
```diff
@@ -619,19 +624,91 @@
...
+                        if (requestLimit - currentGroupSize >= file.size) {
+                            currentGroup.push(file);
+                            currentGroupSize += file.size;
+                        } else {
+                            fileGroups.push(currentGroup);
+                            currentGroupSize = file.size;
+                            currentGroup = [file];
+                        }
+                    }
+                    fileGroups.push(currentGroup);
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:674]: Seems like it could be rewritten with reduce in more pleasant way :)

File: cvat-core/src/server-proxy.js [hunk 11]
```diff
@@ -619,19 +624,91 @@
...
+                    const totalChunks = fileGroups.length;
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.js:675]: Would rename to ``totalBulks``

File: cvat/apps/engine/views.py [hunk 12]
```diff
@@ -616,10 +614,32 @@ def data(self, request, pk):
                     status=status.HTTP_400_BAD_REQUEST)
             serializer = DataSerializer(data=request.data)
             serializer.is_valid(raise_exception=True)
+            data = {k: v for k, v in serializer.validated_data.items()}
+
+            tmp_path = os.path.join('./data/tmp', pk)
```
Comment (bsekachev) [inline cvat/apps/engine/views.py:619]: What is current directory ``.``?  I think we shouldn't operate relative paths here.

File: cvat/apps/engine/views.py [hunk 13]
```diff
@@ -616,10 +614,32 @@ def data(self, request, pk):
...
+            os.makedirs(tmp_path, exist_ok=True)
+            if data.get('use_chunk_upload'): # write chunk
+                with open(os.path.join(tmp_path, data.get('chunk_file_name')), 'ab+') as destination:
```
Comment (bsekachev) [inline cvat/apps/engine/views.py:622]: If ``chunk_file_name`` exists, ``use_chunk_upload`` also always true, right? 
I think ``use_chunk_upload`` is extra here.

File: cvat/apps/engine/views.py [hunk 14]
```diff
@@ -616,10 +614,32 @@ def data(self, request, pk):
...
+                    destination.write(data.get('client_files')[0]['file'].read())
+            else: # write each file
+                for client_file in data.get('client_files'):
+                    with open(os.path.join(tmp_path, client_file['file'].name), 'ab+') as destination:
+                        destination.write(client_file['file'].read())
+            if 'end_of_upload' in request.data and not data.get('end_of_upload'):
+                return Response(data='Chunk is delivered', status=status.HTTP_202_ACCEPTED)
```
Comment (bsekachev) [inline cvat/apps/engine/views.py:629]: Do you need this response text ``Chunk is delivered``? I think status with code is enough

File: cvat-core/src/server-proxy.js (hunk 1 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done.

File: cvat-core/src/server-proxy.js (hunk 2 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 3 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 4 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 5 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 6 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 7 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 8 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: No, we cant get it from the file but there is a way to set up name to the chunk using `taskData.set(client_files[0], fileChunk, 'filename.mp4')`

File: cvat-core/src/server-proxy.js (hunk 9 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 10 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat-core/src/server-proxy.js (hunk 11 above)
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Done

File: cvat/apps/engine/views.py (hunk 12 above)
Comment (klakhov) [reply cvat/apps/engine/views.py]: Changed to relative path

File: cvat/apps/engine/views.py (hunk 13 above)
Comment (klakhov) [reply cvat/apps/engine/views.py]: Removed

File: cvat/apps/engine/views.py (hunk 14 above)
Comment (klakhov) [reply cvat/apps/engine/views.py]: Removed

**Comment by nmanovic** [comment]
Some resources and ideas:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html
- https://github.com/juliomalegria/django-chunked-upload

File: cvat/apps/engine/views.py [hunk 15]
```diff
@@ -616,10 +614,38 @@ def data(self, request, pk):
                     status=status.HTTP_400_BAD_REQUEST)
             serializer = DataSerializer(data=request.data)
             serializer.is_valid(raise_exception=True)
+            data = {k: v for k, v in serializer.validated_data.items()}
+
+            tmp_path = os.path.join(settings.TMP_DATA_ROOT, pk)
```
Comment (nmanovic) [inline cvat/apps/engine/views.py:619]: @klakhov , what is the reason to upload into a temporary directory? Why don't upload directly to upload_dir?

File: cvat/apps/engine/views.py [hunk 16]
```diff
@@ -616,10 +614,38 @@ def data(self, request, pk):
...
+            os.makedirs(tmp_path, exist_ok=True)
```
Comment (nmanovic) [inline cvat/apps/engine/views.py:620]: @klakhov , What if several tasks are created in parallel? Can they override data of each other?

File: cvat/apps/engine/views.py (hunk 15 above)
Comment (klakhov) [reply cvat/apps/engine/views.py:619]: The idea behind using tmp directory is that we are uploading files before creating task in database. So, if task is not created, we dont have access to upload_dir.
It is possible to change this logic to: create task, upload data to upload_dir, update data in database. Would it be the best choice?

File: cvat/apps/engine/views.py (hunk 16 above)
Comment (klakhov) [reply cvat/apps/engine/views.py:620]: @nmanovic, There are no problems with that. There is separate tmp directory for each task in `data/tmp/<tid>`

**Comment by bsekachev** [comment]
Tried this patch uploading several videos, images, and archives. Didn't meet any issues

File: cvat-core/src/server-proxy.js [hunk 17]
```diff
@@ -618,9 +634,97 @@
...
 
-                onUpdate('The data are being uploaded to the server..');
+                onUpdate('The data are being uploaded to the server 0%');
+
+                async function chunkUpload(taskId, file) {
+                    const initChunkUpload = await Axios.post(`${backendAPI}/tasks/${response.data.id}/data`,
+                        taskData, {
+                            proxy: config.proxy,
+                            params: {
+                                action: 'init-chunk-upload',
```
Comment (nmanovic) [inline cvat-core/src/server-proxy.js:644]: @klakhov , why here `init-chunk-upload` action is a part of body and `submit` action is a query parameter?

**Comment by nmanovic** [comment]
It looks like the feature is bigger than we thought. For example, it PR will break CLI. Need to fix that. Thus we need to implement the logic in Python and JavaScript. Thus I will recommend to use tus.io as @zhiltsov-max suggested.

1. JS client:  https://github.com/tus/tus-js-client
2. Py client: https://github.com/tus/tus-py-client

We don't have an official server version for Django or DRF. Thus I will recommend to look at django-tus under MIT license and implement our own version.
3. Py server: https://github.com/alican/django-tus

**Comment by nmanovic** [comment]
@klakhov , I see that you have fixed only uploading data for tasks. I'm fine if you want to split the PR on several parts and implement huge file upload for other endpoints later.

**Review by nmanovic — CHANGES_REQUESTED** [review]

File: cvat/apps/engine/mixins.py [hunk 18]
```diff
@@ -0,0 +1,228 @@
...
+        'Cache-Control': 'no-store'
+    }
+    _file_id_regex = r'(?P<file_id>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)'
+
+    def _tus_response(self, extra_headers=None, *args, **kwargs):
+        response = HttpResponse(*args, **kwargs)
+        for key, value in self._base_tus_headers.items():
+            response.__setitem__(key, value)
+        if extra_headers:
+            for key, value in extra_headers.items():
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py:110]: No, it won't work. HttpResponse and DRF Response store headers as(code from response.py constructor):
```
        if headers:
            for name, value in headers.items():
                self[name] = value
```

File: cvat/apps/engine/mixins.py [hunk 19]
```diff
@@ -0,0 +1,228 @@
...
+        'Access-Control-Allow-Origin': "*",
+        'Access-Control-Allow-Methods': "PATCH,HEAD,GET,POST,OPTIONS",
+        'Access-Control-Expose-Headers': "Tus-Resumable,upload-length,upload-metadata,Location,Upload-Offset",
+        'Access-Control-Allow-Headers': "Tus-Resumable,upload-length,upload-metadata,Location,Upload-Offset,content-type",
+        'Cache-Control': 'no-store'
+    }
+    _file_id_regex = r'(?P<file_id>\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b)'
+
+    def _tus_response(self, extra_headers=None, *args, **kwargs):
+        response = HttpResponse(*args, **kwargs)
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: Done

File: cvat/apps/engine/mixins.py [hunk 20]
```diff
@@ -0,0 +1,228 @@
...
+        for key, value in self._base_tus_headers.items():
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py:107]: No, it won't work. HttpResponse and DRF Response store headers as(code from response.py constructor):
```
        if headers:
            for name, value in headers.items():
                self[name] = value
```

File: cvat/apps/engine/mixins.py [hunk 21]
```diff
@@ -0,0 +1,228 @@
...
+        return tus_file
+
+class TusChunk:
+    def __init__(self, request):
+        self.META = request.META
+        self.offset = int(request.META.get("HTTP_UPLOAD_OFFSET", 0))
+        self.size = int(request.META.get("CONTENT_LENGTH", 102400))
+        self.content = request.body
+
+class UploadMixin(object):
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py:87]: Done.

File: cvat/apps/engine/mixins.py [hunk 22]
```diff
@@ -0,0 +1,228 @@
...
+            file.write(chunk.content)
+        self.offset = cache.incr("tus-uploads/{}/offset".format(self.file_id), chunk.size)
+
+    def is_complete(self):
+        return self.offset == self.file_size
+
+    def rename(self):
+        file_id_path = os.path.join(self.upload_dir, self.file_id)
+        file_path = os.path.join(self.upload_dir, self.filename)
+        file_exists = os.path.lexists(os.path.join(self.upload_dir, self.filename))
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py:46]: No, it cant. When tus upload is initialized filename is validated. there is validate_filename method:
```
    def validate_filename(self, filename):
        upload_dir = self.get_upload_dir()
        file_path = os.path.join(upload_dir, filename)
        return os.path.commonprefix((os.path.realpath(file_path), upload_dir)) == upload_dir
```

File: cvat/apps/engine/mixins.py [hunk 23]
```diff
@@ -0,0 +1,228 @@
...
+        if file_exists:
+            raise FileExistsError
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: Done.

File: cvat/apps/engine/mixins.py [hunk 24]
```diff
@@ -0,0 +1,228 @@
...
+        self.offset = cache.get("tus-uploads/{}/offset".format(file_id))
+
+    def init_file(self):
+        file_path = os.path.join(self.upload_dir, self.file_id)
+        with open(file_path, 'wb') as file:
+            file.seek(self.file_size - 1)
+            file.write(b'\0')
+
+    def write_chunk(self, chunk):
+        file_path = os.path.join(self.upload_dir, self.file_id)
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: Done.

File: cvat/apps/engine/mixins.py [hunk 25]
```diff
@@ -0,0 +1,228 @@
...
+                    destination.write(client_file['file'].read())
+        return Response(status=status.HTTP_200_OK)
+
+    @action(detail=True, methods=['POST'], url_path='data/finish')
+    def finish(self, request, pk):
+        return self.upload_finished(request)
+
+    # override this to do stuff after upload
+    def upload_finished(self, request):
+        return Response(status=status.HTTP_200_OK)
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: Done.

File: cvat/apps/engine/mixins.py [hunk 26]
```diff
@@ -0,0 +1,228 @@
...
+        self.META = request.META
+        self.offset = int(request.META.get("HTTP_UPLOAD_OFFSET", 0))
+        self.size = int(request.META.get("CONTENT_LENGTH", 102400))
+        self.content = request.body
+
+class UploadMixin(object):
+    _tus_api_version = '1.0.0'
+    _tus_api_version_supported = ['1.0.0']
+    _tus_api_extensions = []
+    _tus_max_file_size = '26843545600' # 25gb
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: There is no explanation of the limit, we can use any size here but tus requires to send max file size to the client. Moved it to settings

File: cvat/apps/engine/mixins.py [hunk 27]
```diff
@@ -0,0 +1,228 @@
...
+
+        tus_file = TusFile(file_id, upload_dir)
+        tus_file.init_file()
+        return tus_file
+
+class TusChunk:
+    def __init__(self, request):
+        self.META = request.META
+        self.offset = int(request.META.get("HTTP_UPLOAD_OFFSET", 0))
+        self.size = int(request.META.get("CONTENT_LENGTH", 102400))
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/mixins.py]: I suppose here we need to use default chunk size. I've added it to settings/base.by as TUS_DEFAULT_CHUNK_SIZE

File: cvat-core/src/server-proxy.js [hunk 28]
```diff
@@ -618,9 +634,97 @@
...
+                                size: file.size,
+                                file_name: file.name,
+                            },
+                        });
+                    const uploadId = initChunkUpload.data;
+                    const totalChunks = Math.ceil(file.size / chunkSize);
+                    let currentChunkNumber = 1;
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Changed to 0

File: cvat-core/src/server-proxy.js [hunk 29]
```diff
@@ -618,9 +634,97 @@
...
+                    const tags = [];
+                    while (currentChunkNumber <= totalChunks) {
+                        const prevChunkNumber = currentChunkNumber - 1;
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: This code was removed

File: cvat-core/src/server-proxy.js [hunk 30]
```diff
@@ -618,9 +634,97 @@
...
+                                proxy: config.proxy,
+                                params: {
+                                    action: 'append',
+                                    upload_id: uploadId,
+                                },
+                            });
+                        const tag = tagResponse.data;
+                        tags.push({ chunk_number: currentChunkNumber, tag });
+                        taskData.delete('client_files[0]');
+                        const sentSize = Math.min(chunkOffset + chunkSize, file.size) - chunkOffset;
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: This code was removed

File: cvat-core/src/server-proxy.js [hunk 31]
```diff
@@ -618,9 +634,97 @@
...
+                        if (chunkSize - lastBulk.size >= file.size) {
+                            lastBulk.files.push(file);
+                            lastBulk.size += file.size;
+                        } else {
+                            fileGroups.push({ files: [file], size: file.size });
+                        }
+                        return fileGroups;
+                    }, [{ files: [], size: 0 }]);
+                    const totalBulks = fileBulks.length;
+                    let currentChunkNumber = 1;
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js]: Changed to 0

File: cvat-core/src/server-proxy.js [hunk 32]
```diff
@@ -618,9 +634,97 @@
...
+                            proxy: config.proxy,
+                        });
+                        for (let i = 0; i < fileBulks[currentChunkNumber - 1].files.length; i++) {
+                            taskData.delete(`client_files[${i}]`);
+                        }
+                        totalSentSize += fileBulks[currentChunkNumber - 1].size;
+                        currentChunkNumber++;
+                    }
+                }
+
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js:717]: It's already done before chunk/bulk uploads

File: cvat/apps/engine/views.py [hunk 33]
```diff
@@ -628,15 +627,62 @@ def jobs(self, request, pk):
...
+            elif action == 'submit' or not action:
+                uploaded_files = task_data.get_uploaded_files()
+                uploaded_files.extend(data.get('client_files'))
+                serializer.validated_data.update({'client_files': uploaded_files})
+
             db_data = serializer.save()
             db_task.data = db_data
             db_task.save()
-            data = {k:v for k, v in serializer.data.items()}
+            data = {k: v for k, v in serializer.data.items()}
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/apps/engine/views.py]: Done. (But we need to use `serilizer.validated_data` or an error is raised)

File: cvat-core/src/server-proxy.js [hunk 34]
```diff
@@ -632,18 +649,95 @@
...
-                onUpdate('The data are being uploaded to the server..');
-                try {
-                    await Axios.post(`${backendAPI}/tasks/${response.data.id}/data`, taskData, {
-                        proxy: config.proxy,
+                onUpdate('The data are being uploaded to the server 0%');
+
+                async function chunkUpload(taskId, file) {
+                    return new Promise((resolve, reject) => {
+                        const upload = new tus.Upload(file, {
+                            endpoint: `${origin}/${backendAPI}/tasks/${taskId}/data/tus/`,
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js:657]: We can remove `/tus/` and `/append/` endpoints with more complicated logic on `/data/` endpoint. But then we need to remove `/finish` too. What is the best way to do it? Check for amount of sent files?

File: cvat-core/src/server-proxy.js [hunk 35]
```diff
@@ -632,18 +649,95 @@
...
+                                totalSentSize += file.size;
+                                resolve();
+                            },
+                        });
+                        upload.start();
                     });
+                }
+
+                async function bulkUpload(taskId, files) {
+                    const fileBulks = files.reduce((fileGroups, file) => {
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js:689]: I don't think reduce looks complicated, here it helps to write less code.

File: cvat-core/src/server-proxy.js [hunk 36]
```diff
@@ -632,18 +649,95 @@
...
+                    }, [{ files: [], size: 0 }]);
+                    const totalBulks = fileBulks.length;
+                    let currentChunkNumber = 1;
+                    while (currentChunkNumber <= totalBulks) {
+                        for (const [idx, element] of fileBulks[currentChunkNumber - 1].files.entries()) {
+                            taskData.append(`client_files[${idx}]`, element);
+                        }
+                        onUpdate(`The data are being uploaded to the server
+                                    ${((totalSentSize / totalSize) * 100).toFixed(2)}%`);
+                        await Axios.post(`${backendAPI}/tasks/${taskId}/data/append`, taskData, {
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js:707]: Let's discuss amount endpoints in conversation about `/tus/` endpoint

File: cvat-core/src/server-proxy.js [hunk 37]
```diff
@@ -632,18 +649,95 @@
...
+                            proxy: config.proxy,
+                        });
+                    for (const file of chunkFiles) {
+                        await chunkUpload(response.data.id, file);
+                    }
+                    if (bulkFiles.length > 0) {
+                        await bulkUpload(response.data.id, bulkFiles);
+                    }
+                    if (chunkFiles.length > 0 || bulkFiles.length > 0) {
+                        await Axios.post(`${backendAPI}/tasks/${response.data.id}/data/finish`,
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat-core/src/server-proxy.js:730]: I don't see any comments with suggestions about it. We can do something based on amount of files or something else. Anyway, i would like to hear what do you think about it.

**Comment by nmanovic** [comment]
@klakhov , 
- the known list of files can be a good heuristics. But in this case we cannot finish upload if by a reason it is not possible to send a file from the list.
- We can also use special acceptance headers (e.g. `Upload-Start` and `Upload-Finish`) like Tus does. It will be a part of our protocol. To support the legacy behaviors we can omit both headers and in the case the single request will be start and end at the same time.

What do you think?

**Comment by klakhov** [comment]
@nmanovic 
I'm fine with that. Lets use headers.

**Comment by klakhov** [comment]
@nmanovic Could you please take a look on updated pr. I've removed `/append`, `/tus`, `/finished` endpoints and used `Upload-Start`, `Upload-Finish`, `Upload-Multiple` headers to indicate request purpose

File: cvat/settings/base.py [hunk 38]
```diff
@@ -482,3 +482,29 @@ def add_ssh_keys():
 
 USE_CACHE = True
 
+CORS_ALLOW_HEADERS = [
```
[the remark this answers is not in the document]
Comment (klakhov) [reply cvat/settings/base.py]: Done.

**Comment by nmanovic** [comment]
@klakhov , could you please resolve conflicts?

**Review by nmanovic — APPROVED** [review]
Great job!

Comments for the future:
1. I saw that in case of bulk upload we have the following operation for each file in python code: open, read, write, close. Probably we can just move them from a temporary location to upload directory. Probably it will be an optimization in the future.
2. Need to update CLI to support the new protocol
3. Need to add the protocol for all other upload operations (import task, import dataset, import project).
