### PR TITLE
Fixed UI fails when inactive user is assigneed to a task/job

### LINKED ISSUE #3339: Can't open a task that is assigned to inactive user
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
There is a bug. In the case you are trying to open a task that is assigned to inactive user (or includes a job that assigned to inactive user):
image

### Steps to Reproduce (for bugs)

1. Create a task, assign it to some active user
2. Change user active status to false
3. Try to open the task

### Your Environment

- cvat version - release v1.3.0
- browser - Google Chrome v.89.0.4389.128

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #3339

### How has this been tested?
Manual testing.
@dvkruchinin Can we prepare a test for the issue?

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: tests/cypress/support/commands_review_pipeline.js [hunk 1]
```diff
@@ -157,7 +155,7 @@ Cypress.Commands.add('submitReview', (decision, user) => {
     cy.get('.cvat-submit-review-dialog').within(() => {
         cy.contains(new RegExp(`^${decision}$`, 'g')).click();
         if (decision === 'Review next') {
-            cy.intercept('GET', `/api/v1/users?is_active=true&search=${user}&limit=10`).as('searchUsers');
+            cy.intercept('GET', `/api/v1/users?search=${user}&limit=10&is_active=true`).as('searchUsers');
```
Comment (bsekachev) [inline tests/cypress/support/commands_review_pipeline.js:158]: @dvkruchinin 
Cypress tests failed because of this line. We do not really control the order of query parameters in these URLs (and probably we do not want to control it). Does cypress require exact order or maybe do you have ideas on how to improve it?

Comment (dvkruchinin) [reply tests/cypress/support/commands_review_pipeline.js:158]: Yes, the order must be followed. But in this case I think it can be processed through wildcard
```
cy.intercept('GET', '/api/v1/users*').as('searchUsers');
```

**Comment by dvkruchinin** [comment]
> Can we prepare a test for the issue?

Yes. A test will be prepared.

**Review by nmanovic — APPROVED** [review]
