### PR TITLE
Fixed copy/paste for rotated shapes

### LINKED ISSUE #4038: Bounding box is copied without rotation
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

The bounding box will be copied with correct rotation
### Current Behaviour

The bounding box is copied without rotation

no_rotation

### Steps to Reproduce (for bugs)

1. create bounding box
1. rotate by some angle
1. copy
1. past 

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by bsekachev**
### How has this been tested?

Resolve #4038

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@dvkruchinin 

Could you please add a test with copy/paste a rotated shape?

**Comment by dvkruchinin** [comment]
> @dvkruchinin
> 
> Could you please add a test with copy/paste a rotated shape?

Sure. I`ll update the corresponding test.

**Review by Marishka17 — APPROVED** [review]
LGTM, but there is one inconsistency.
inconsistency

**Comment by bsekachev** [comment]
@Marishka17 That is not ``inconsistency``. Just text cannot be placed right of the first shape because in this case it is out of canvas.

File: tests/cypress/integration/actions_objects/case_60_autoborder_feature.js [hunk 1]
```diff
@@ -67,11 +63,6 @@ context('Autoborder feature.', () => {
             });
     }
 
-    function testActivatingShape(x, y, expectedShape) {
-        cy.get('.cvat-canvas-container').trigger('mousemove', x, y);
-        cy.get(expectedShape).should('have.class', 'cvat_canvas_shape_activated');
-    }
```
Comment (Marishka17) [inline tests/cypress/integration/actions_objects/case_60_autoborder_feature.js:73]: Why did you remove this check?

Comment (bsekachev) [reply tests/cypress/integration/actions_objects/case_60_autoborder_feature.js:73]: Because it is not necessary anymore. Previous test implementation activated shapes to get coordinates of circles. 
These coordinates needed to check final result. The test worked this way, but it was a kind of lucky. Circles for different shapes are located in different coordinate spaces and comparing them is incorrect way. Two points in different places on canvas can have the same coordinates (0,0 for example). I've rewritten the test and now it gets correct position from shape attributes.

**Review by Marishka17 — APPROVED** [review]
