### PR TITLE
Project tasks loading only when needed

### LINKED ISSUE #3128: With big amount of projects/tasks Projects page get slow to open and makes too much api and db requests
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Projects page opens fast and not make unnecessary web and db requests. 

### Current Behaviour
It was faster in the beginning but with growing number of projects and tasks it get slower and slower. 
Right now to open Projects it takes 30+ seconds. 

In browsers dev tools it shows what /projects request takes 30 seconds to complete and then followed by huge amount of /data?type=preview requests. 

<a href="https://ibb.co/Dp3LPRH">projects-network-list1</a>

Also with enabled query logging on db. It logs like 30000+ sql select queries just when Projects page requested. 
To get this logs I add this to compose config 
```
    container_name: cvat_db
    image: postgres:10-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
```
refreshed page in browser and saved logs by
`docker logs 5278709de3c0 &> sql.log.txt`

### Your Environment

- Git hash commit (`git log -1`): 17908003df9565bab02120c38834023f31eef494
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.5, build 55c4c88
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Window locally and ubuntu on vps. 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

Resolve #3128. Trying to avoid unnecessary requests while fetching projects API.

### How has this been tested?

Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@ActiveChooN 
Could you please look at remark lint issues and to cypress tests related with projects? (actions_projects)? They should not failed. 

@dvkruchinin 
Probably the tests in issues_prs and canvas3d_functionality should not be affected by this patch. It is not clear why them failed. Could you please take a look?

**Comment by dvkruchinin** [comment]
@bsekachev 
> Probably the tests in issues_prs and canvas3d_functionality should not be affected by this patch. It is not clear why them failed. Could you please take a look?

Sure. I`ll take a look.

File: cvat-ui/src/actions/projects-actions.ts [hunk 1]
```diff
@@ -69,6 +69,12 @@ export function getProjectsAsync(query: Partial<ProjectsQuery>): ThunkAction {
             page: 1,
             ...query,
         };
+
+        // Check if we try to retrive single project of projects list
+        if (!Object.keys(filteredQuery).includes('id')) {
+            filteredQuery.withoutTasks = true;
+        }
```
Comment (bsekachev) [inline cvat-ui/src/actions/projects-actions.ts:76]: Maybe it is better to do it on cvat-core level?

File: cvat-ui/src/actions/projects-actions.ts [hunk 2]
```diff
@@ -85,38 +91,39 @@ export function getProjectsAsync(query: Partial<ProjectsQuery>): ThunkAction {
...
-                    name: null,
-                    owner: null,
-                    search: null,
-                    status: null,
-                }),
-            );
+            const taskPreviews = await Promise.all(taskPreviewPromises);
+
+            const store = getCVATStore();
+            const state: CombinedState = store.getState();
```
Comment (bsekachev) [inline cvat-ui/src/actions/projects-actions.ts:106]: Just if you did not know, ``getState`` is the second argument of async action creator, after ``dispatch``.

File: cvat-ui/src/components/project-page/project-page.tsx [hunk 3]
```diff
@@ -28,18 +28,16 @@ export default function ProjectPageComponent(): JSX.Element {
     const id = +useParams<ParamType>().id;
     const dispatch = useDispatch();
     const history = useHistory();
-    const projects = useSelector((state: CombinedState) => state.projects.current);
+    const projects = useSelector((state: CombinedState) => state.projects.current.map((project) => project.instance));
```
Comment (bsekachev) [inline cvat-ui/src/components/project-page/project-page.tsx:31]: We should not use .map in useSelector. It creates unnecessary rerenders because useSelector always return new object.

File: cvat-core/src/api-implementation.js [hunk 4]
```diff
@@ -238,6 +238,7 @@
             // prettier-ignore
             const projects = projectsData.map((project) => {
                 if (filter.withoutTasks) {
+                    project.task_ids = project.tasks;
```
Comment (bsekachev) [inline cvat-core/src/api-implementation.js:241]: If it is fetched with tasks, I would prefer intiailize this field also ``project.task_ids = project.tasks.map((task) => task.id);``
In this case ``Project.prototype.preview.implementation`` can be significantly simplified.

File: cvat-ui/src/actions/projects-actions.ts (hunk 1 above)
Comment (bsekachev) [reply cvat-ui/src/actions/projects-actions.ts:76]: In this case we do not need ``withoutTasks`` option. The benefit of it is that ``withoutTasks`` is use only by internal code and it is not fully clear why we need it as a part of API.

File: cvat-ui/src/components/project-page/project-page.tsx [hunk 5]
```diff
@@ -28,18 +28,16 @@ export default function ProjectPageComponent(): JSX.Element {
...
     const taskDeletes = useSelector((state: CombinedState) => state.tasks.activities.deletes);
     const tasksActiveInferences = useSelector((state: CombinedState) => state.models.inferences);
     const tasks = useSelector((state: CombinedState) => state.tasks.current);
-    const projectSubsets = useSelector((state: CombinedState) => {
-        const [project] = state.projects.current.filter((_project) => _project.id === id);
-        return project ? ([...new Set(project.tasks.map((task: any) => task.subset))] as string[]) : [];
-    });
 
     const [project] = projects.filter((_project) => _project.id === id);
+    const projectSubsets = [''];
```
Comment (bsekachev) [inline cvat-ui/src/components/project-page/project-page.tsx:39]: ``No subset assigned``?

**Comment by bsekachev** [comment]
BTW, should not we paginate project tasks? Now it lists (and fetches from the server) all the tasks. It is probably inefficient. Another question is how to list such tasks considering several subsets.

File: cvat-ui/src/components/project-page/project-page.tsx (hunk 3 above)
Comment (bsekachev) [inline cvat-ui/src/components/project-page/project-page.tsx:31]: Probably is an option:

```
    const projects = useSelector((state: CombinedState) => state.projects.current)).map((project) => project.instance;
```

**Comment by dvkruchinin** [comment]
I looked at it. This is similar to a situation that has already occurred (https://github.com/openvinotoolkit/cvat/pull/3001/files). In this PR, a horizontal scroll bar appears.
Crop polygon properly -- Testing issue 2992 -- Draw a polygon with vertices outside the image (failed)

**Comment by ActiveChooN** [comment]
> 
> 
> @ActiveChooN
> Could you please look at remark lint issues and to cypress tests related with projects? (actions_projects)? They should not failed.
> 
> @dvkruchinin
> Probably the tests in issues_prs and canvas3d_functionality should not be affected by this patch. It is not clear why them failed. Could you please take a look?

Remark lint failed due to empty bullet list items. I Will check other related test failures.

> BTW, should not we paginate project tasks?

Yes, it's a good idea. And better way to do it on a server and just to order tasks by subset and filter by project, then cache responses on a client. But it looks like a separate feature.

File: cvat-ui/src/components/project-page/project-page.tsx (hunk 5 above)
Comment (ActiveChooN) [reply cvat-ui/src/components/project-page/project-page.tsx:39]: It's a default value for the task without a subset.

File: cvat-ui/src/actions/projects-actions.ts (hunk 2 above)
Comment (ActiveChooN) [reply cvat-ui/src/actions/projects-actions.ts:106]: Thanks

File: cvat-ui/src/components/project-page/styles.scss [hunk 6]
```diff
@@ -54,3 +54,7 @@
     display: flex;
     align-items: center;
 }
+
+.ant-layout-content {
+    overflow-y: auto;
+}
```
Comment (bsekachev) [inline cvat-ui/src/components/project-page/styles.scss:60]: @ActiveChooN 

Looks like this change breaks the tests. Horizontal line appears at the bottom as @dvkruchinin mentioned.

File: cvat-ui/src/actions/projects-actions.ts (hunk 1 above)
Comment (ActiveChooN) [reply cvat-ui/src/actions/projects-actions.ts]: Made `withoutTasks` parameter computable.

File: cvat-ui/src/components/project-page/styles.scss (hunk 6 above)
Comment (ActiveChooN) [reply cvat-ui/src/components/project-page/styles.scss:60]: Ok, but without it, the project page looks strange and inconsistent.

*Before*
изображение

*After*
изображение

File: cvat-ui/src/components/project-page/project-page.tsx (hunk 5 above)
Comment (bsekachev) [reply cvat-ui/src/components/project-page/project-page.tsx:39]: Yes, just on UI we could rename it as we wish for better UX, right?

**Review by bsekachev — APPROVED** [review]
